#!/usr/bin/env bash
# install_hooks.sh — installer шаблонного post-commit хука cognitive OS
# во все git-репозитории под $PROJECTS_ROOT.
#
# Стратегия:
#   — если в .git/hooks/post-commit ничего нет — ставим симлинк на
#     scripts/project_post_commit.sh (DRY, обновление одного файла = обновление
#     везде);
#   — если уже есть наш хук (симлинк на наш скрипт ИЛИ chain-wrapper с
#     маркером COGNITIVE-OS-HOOK-MARKER) — idempotent-skip;
#   — если есть чужой хук — по умолчанию skip + отчёт с конкретной командой
#     (--chain <repo> или --force <repo>);
#   — `--auto-chain-when-safe` — автоматически делать chain, если старый
#     хук безопасен (bash-shebang, нет exit в середине);
#   — `--force <repo>` — бэкап старого в post-commit.bak-<ts> и поставить наш
#     симлинк точечно;
#   — `--chain <repo>` — создать chain-wrapper точечно;
#   — `--dry-run` — показать действия без записи;
#   — `--inspect <repo>` — показать содержимое существующего хука;
#   — `--init-ids` — интерактивно проставить `project_id` в CLAUDE.md тех
#     проектов, где его нет.
#
# Exit code: 0 если всё ок или только идемпотентные skip; 1 если были
# ошибки установки.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_SOURCE="$SCRIPT_DIR/project_post_commit.sh"
PROJECTS_ROOT="${PROJECTS_ROOT:-$HOME/Documents/Claude/Projects}"
HOOK_MARKER="COGNITIVE-OS-HOOK-MARKER=project_post_commit"

# --- парсинг аргументов ---------------------------------------------------

DRY_RUN=0
AUTO_CHAIN_SAFE=0
INIT_IDS=0
FORCE_PATH=""
CHAIN_PATH=""
INSPECT_PATH=""

usage() {
    cat <<EOF
Usage: install_hooks.sh [OPTIONS]

Default (no args): установить во все репозитории под
  $PROJECTS_ROOT

Options:
  --dry-run                        показать действия без записи
  --auto-chain-when-safe           auto-chain для явно-безопасных хуков
  --force <repo>                   точечно: backup существующего + наш симлинк
  --chain <repo>                   точечно: chain-wrapper (старый → наш)
  --inspect <repo>                 показать существующий хук
  --init-ids                       интерактивно проставить project_id

Переменная окружения:
  PROJECTS_ROOT                    корень для поиска репо (по умолчанию
                                   ~/Documents/Claude/Projects)
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)                DRY_RUN=1; shift ;;
        --auto-chain-when-safe)   AUTO_CHAIN_SAFE=1; shift ;;
        --init-ids)               INIT_IDS=1; shift ;;
        --force)                  FORCE_PATH="${2:?--force requires repo path}"; shift 2 ;;
        --chain)                  CHAIN_PATH="${2:?--chain requires repo path}"; shift 2 ;;
        --inspect)                INSPECT_PATH="${2:?--inspect requires repo path}"; shift 2 ;;
        -h|--help)                usage; exit 0 ;;
        *)                        echo "Unknown option: $1" >&2; usage; exit 2 ;;
    esac
done

# --- sanity: исходный хук --------------------------------------------------

if [[ ! -f "$HOOK_SOURCE" ]]; then
    echo "ERROR: hook source not found: $HOOK_SOURCE" >&2
    exit 2
fi
chmod +x "$HOOK_SOURCE" 2>/dev/null || true

# --- утилиты ---------------------------------------------------------------

log_action() {
    local tag="$1"; shift
    printf '[%s] %s\n' "$tag" "$*"
}

is_our_hook() {
    local hook="$1"
    if [[ -L "$hook" ]]; then
        local target
        target="$(readlink "$hook")"
        [[ "$target" == *"project_post_commit.sh"* ]] && return 0
    fi
    if [[ -f "$hook" ]] && grep -q "$HOOK_MARKER" "$hook" 2>/dev/null; then
        return 0
    fi
    return 1
}

is_safe_bash_hook() {
    # Эвристика: shebang на bash/sh, нет вызовов exec/exit посреди файла.
    local hook="$1"
    [[ -f "$hook" ]] || return 1
    local first_line
    first_line="$(head -n1 "$hook" 2>/dev/null || true)"
    case "$first_line" in
        '#!/bin/bash'|'#!/usr/bin/env bash'|'#!/bin/sh'|'#!/usr/bin/env sh') ;;
        *) return 1 ;;
    esac
    # Считаем exit/exec в середине (не в последней строке) как риск.
    local total_lines body_lines
    total_lines="$(wc -l < "$hook" | tr -d ' ')"
    body_lines="$((total_lines > 0 ? total_lines - 1 : 0))"
    if [[ "$body_lines" -gt 0 ]]; then
        if head -n "$body_lines" "$hook" | grep -Eq '^\s*(exit|exec)\b'; then
            return 1
        fi
    fi
    return 0
}

write_chain_wrapper() {
    # $1 = hook path, $2 = backup path of existing hook
    local hook="$1"
    local backup="$2"
    cat > "$hook" <<EOF
#!/usr/bin/env bash
# $HOOK_MARKER (chain-wrapper)
# Auto-generated by install_hooks.sh — do not edit by hand.
# Original hook preserved at: $backup
set +e
if [[ -x "$backup" ]]; then
    "$backup" "\$@"
fi
"$HOOK_SOURCE" "\$@"
exit 0
EOF
    chmod +x "$hook"
}

install_symlink() {
    # $1 = hook path
    local hook="$1"
    ln -sf "$HOOK_SOURCE" "$hook"
}

backup_existing() {
    # $1 = hook path → prints backup path
    local hook="$1"
    local ts backup
    ts="$(date '+%Y-%m-%d-%H%M%S')"
    backup="${hook}.bak-${ts}"
    mv "$hook" "$backup"
    printf '%s\n' "$backup"
}

# --- точечные режимы -------------------------------------------------------

run_inspect() {
    local repo="$1"
    local hook="$repo/.git/hooks/post-commit"
    if [[ ! -e "$hook" ]]; then
        echo "no post-commit hook at $hook"
        return 0
    fi
    echo "=== $hook ==="
    if [[ -L "$hook" ]]; then
        echo "(symlink → $(readlink "$hook"))"
    fi
    wc -l "$hook" | awk '{print "lines:", $1}'
    echo "--- content ---"
    cat "$hook"
    echo "--- end ---"
}

run_force_single() {
    local repo="$1"
    local hook="$repo/.git/hooks/post-commit"
    if [[ ! -d "$repo/.git" ]]; then
        echo "ERROR: $repo is not a git repo" >&2; return 1
    fi
    mkdir -p "$repo/.git/hooks"
    if [[ -e "$hook" ]] && ! is_our_hook "$hook"; then
        if [[ "$DRY_RUN" -eq 1 ]]; then
            log_action DRY "would backup $hook"
        else
            backup="$(backup_existing "$hook")"
            log_action BACKUP "$hook → $backup"
        fi
    fi
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log_action DRY "would symlink $hook → $HOOK_SOURCE"
    else
        install_symlink "$hook"
        log_action OK "$repo — installed (force)"
    fi
}

run_chain_single() {
    local repo="$1"
    local hook="$repo/.git/hooks/post-commit"
    if [[ ! -d "$repo/.git" ]]; then
        echo "ERROR: $repo is not a git repo" >&2; return 1
    fi
    if [[ ! -f "$hook" ]]; then
        echo "ERROR: no existing hook to chain at $hook" >&2; return 1
    fi
    if is_our_hook "$hook"; then
        log_action SKIP "$repo — already ours"
        return 0
    fi
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log_action DRY "would chain $hook (backup + wrapper)"
        return 0
    fi
    backup="$(backup_existing "$hook")"
    chmod +x "$backup" 2>/dev/null || true
    write_chain_wrapper "$hook" "$backup"
    log_action OK "$repo — chained (original → $backup)"
}

# --- init-ids режим --------------------------------------------------------

run_init_ids() {
    echo "== init-ids: проверка frontmatter project_id в CLAUDE.md =="
    local vault="${CLAUDE_WORKSPACE:-$HOME/Documents/Claude/cognitive_os}"
    local known=()
    if [[ -d "$vault/projects" ]]; then
        while IFS= read -r -d '' d; do
            known+=("$(basename "$d")")
        done < <(find "$vault/projects" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null)
    fi
    echo "Известные proj-NNN в vault: ${known[*]:-<нет>}"
    echo

    shopt -s nullglob
    local any_missing=0
    for repo in "$PROJECTS_ROOT"/*; do
        [[ -d "$repo/.git" ]] || continue
        local cm="$repo/CLAUDE.md"
        local name
        name="$(basename "$repo")"
        local pid=""
        if [[ -f "$cm" ]]; then
            pid="$(awk '
                BEGIN { in_fm=0; seen=0 }
                /^---[[:space:]]*$/ { if (!seen) { in_fm=1; seen=1; next } else { exit } }
                in_fm && /^project_id:/ {
                    sub(/^project_id:[[:space:]]*/, ""); sub(/[[:space:]]+$/, "")
                    gsub(/["'\'']/, ""); print; exit
                }' "$cm")"
        fi
        if [[ -n "$pid" ]]; then
            echo "  [ok] $name → $pid"
            continue
        fi
        any_missing=1
        echo "  [??] $name — нет project_id в CLAUDE.md"
        if [[ "$DRY_RUN" -eq 1 ]]; then
            echo "       DRY-RUN: пропуск ввода"
            continue
        fi
        read -r -p "       Введите proj-NNN (Enter — пропустить): " chosen
        if [[ -z "$chosen" ]]; then
            echo "       пропущено"
            continue
        fi
        # Добавить/создать frontmatter
        if [[ ! -f "$cm" ]]; then
            cat > "$cm" <<EOF
---
project_id: $chosen
---

# $name

EOF
            echo "       создан CLAUDE.md с project_id: $chosen"
        elif head -n1 "$cm" | grep -q '^---[[:space:]]*$'; then
            # уже есть frontmatter — вставим project_id после первой ---
            local tmp
            tmp="$(mktemp)"
            awk -v pid="$chosen" '
                BEGIN { inserted=0 }
                NR==1 && /^---[[:space:]]*$/ { print; print "project_id: " pid; inserted=1; next }
                { print }
            ' "$cm" > "$tmp" && mv "$tmp" "$cm"
            echo "       project_id: $chosen добавлен в существующий frontmatter"
        else
            # файл без frontmatter — обернём
            local tmp
            tmp="$(mktemp)"
            { printf -- '---\nproject_id: %s\n---\n\n' "$chosen"; cat "$cm"; } > "$tmp" && mv "$tmp" "$cm"
            echo "       frontmatter с project_id: $chosen добавлен сверху"
        fi
    done
    shopt -u nullglob
    if [[ "$any_missing" -eq 0 ]]; then
        echo "Все проекты уже имеют project_id. Ничего не меняю."
    fi
}

# --- ветвления по режиму ---------------------------------------------------

if [[ -n "$INSPECT_PATH" ]]; then run_inspect "$INSPECT_PATH"; exit 0; fi
if [[ -n "$FORCE_PATH"   ]]; then run_force_single "$FORCE_PATH"; exit $?; fi
if [[ -n "$CHAIN_PATH"   ]]; then run_chain_single "$CHAIN_PATH"; exit $?; fi
if [[ "$INIT_IDS" -eq 1  ]]; then run_init_ids; exit 0; fi

# --- batch-режим: пройти по всем репо под PROJECTS_ROOT --------------------

if [[ ! -d "$PROJECTS_ROOT" ]]; then
    echo "ERROR: PROJECTS_ROOT not found: $PROJECTS_ROOT" >&2
    exit 2
fi

INSTALLED=()
ALREADY=()
SKIPPED_CONFLICT=()
CHAINED_AUTO=()
ERRORS=()

shopt -s nullglob
for repo in "$PROJECTS_ROOT"/*; do
    [[ -d "$repo/.git" ]] || continue
    hook_dir="$repo/.git/hooks"
    hook="$hook_dir/post-commit"
    if [[ "$DRY_RUN" -eq 0 ]]; then
        mkdir -p "$hook_dir"
    fi

    if [[ -e "$hook" ]]; then
        if is_our_hook "$hook"; then
            ALREADY+=("$repo")
            continue
        fi
        # чужой хук
        if [[ "$AUTO_CHAIN_SAFE" -eq 1 ]] && is_safe_bash_hook "$hook"; then
            if [[ "$DRY_RUN" -eq 1 ]]; then
                CHAINED_AUTO+=("$repo (DRY)")
            else
                backup="$(backup_existing "$hook")"
                chmod +x "$backup" 2>/dev/null || true
                write_chain_wrapper "$hook" "$backup"
                CHAINED_AUTO+=("$repo")
            fi
            continue
        fi
        SKIPPED_CONFLICT+=("$repo")
        continue
    fi

    # хука нет — ставим симлинк
    if [[ "$DRY_RUN" -eq 1 ]]; then
        INSTALLED+=("$repo (DRY)")
    else
        if install_symlink "$hook"; then
            INSTALLED+=("$repo")
        else
            ERRORS+=("$repo")
        fi
    fi
done
shopt -u nullglob

# --- отчёт -----------------------------------------------------------------

echo
echo "=== install_hooks.sh — отчёт ==="
printf 'PROJECTS_ROOT : %s\n' "$PROJECTS_ROOT"
printf 'HOOK_SOURCE   : %s\n' "$HOOK_SOURCE"
[[ "$DRY_RUN" -eq 1 ]] && echo "(dry-run: файлы не изменялись)"
echo
echo "Установлено (новый симлинк): ${#INSTALLED[@]}"
for r in "${INSTALLED[@]:-}"; do printf '  - %s\n' "$r"; done
echo "Уже наш хук (idempotent skip): ${#ALREADY[@]}"
for r in "${ALREADY[@]:-}"; do printf '  - %s\n' "$r"; done
echo "Auto-chained (безопасный bash): ${#CHAINED_AUTO[@]}"
for r in "${CHAINED_AUTO[@]:-}"; do printf '  - %s\n' "$r"; done
echo "Пропущено (чужой хук): ${#SKIPPED_CONFLICT[@]}"
for r in "${SKIPPED_CONFLICT[@]:-}"; do
    printf '  - %s\n' "$r"
    printf '      варианты: install_hooks.sh --chain %q\n' "$r"
    printf '                install_hooks.sh --force %q\n' "$r"
    printf '                install_hooks.sh --inspect %q\n' "$r"
done
echo "Ошибки: ${#ERRORS[@]}"
for r in "${ERRORS[@]:-}"; do printf '  - %s\n' "$r"; done

if [[ "${#ERRORS[@]}" -gt 0 ]]; then
    exit 1
fi
exit 0
